# Generated by Django 3.2.5 on 2023-12-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='referencenumber',
            field=models.CharField(help_text='reference number', max_length=20, primary_key=True, serialize=False),
        ),
    ]
